[platformio]
src_dir = src
include_dir = include

[env:esp32cam_ai_thinker]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -D CAMERA_MODEL_AI_THINKER
